### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by mleinart** [markchadwick/graphite-relay#3]
I would like to use some of your code to implement some load tests against Graphite using Iago (https://github.com/twitter/iago) but wont be able to publish them unless you declare a license. Without specifying, the copyright defaults to 'all rights reserved'.

Can you take a moment to drop a LICENSE file you like in the repo? It'd be much appreciated :)

**Comment by markchadwick** [comment]
There ya go. Apache 2.0. Thanks!
