### ISSUE TITLE
Too many CLOSE_WAIT connections

### ISSUE THREAD

**Issue by deniszh** [markchadwick/graphite-relay#5]
After some running (20 minutes) on our test environment I fount that relay open tons of connections to client:
root@graph:/# netstat -apn | grep 25782 | grep ESTA | wc -l
1297
root@graph:/# netstat -apn | grep 25782 | grep CLOS | wc -l
2669
As far as I understand these connections are holded by Netty. How can I mitigate this?

Thanks!

**Comment by markchadwick** [comment]
Unfortunately, I don't know of any way to fix this in process. However, you can get the OS to reuse those sockets instead of leaving them in CLOSE_WAIT: http://lxr.linux.no/linux+v3.2.8/Documentation/networking/ip-sysctl.txt#L464

**Comment by deniszh** [comment]
Btw issue is totally gone after using Netty 3.7.0.Final:
root@graph:~# netstat -apn | grep 2003 | grep CLOSE |wc -l
0
root@graph:~# netstat -apn | grep 2003 | grep ESTA |wc -l
127
